name: CI Pipeline

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          make install

      - name: Format
        run: |
          make format

      - name: Lint code
        run: |
          make lint

      - name: Run tests
        run: |
          make test
